import * as core from "@actions/core";
import * as github from "@actions/github";
import { GoogleGenerativeAI } from "@google/generative-ai";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
const MODEL = "gemini-2.5-flash";
const MAX_DIFF_CHARS = 30_000; // truncate very large diffs to stay within context limits
const COMMENT_MARKER = "<!-- pr-summarizer-bot -->";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Fetch the raw unified diff for a pull request.
 * @param {ReturnType<typeof github.getOctokit>} octokit
 * @param {{ owner: string; repo: string; pull_number: number }} params
 * @returns {Promise<string>}
 */
async function fetchPrDiff(octokit, { owner, repo, pull_number }) {
  const response = await octokit.rest.pulls.get({
    owner,
    repo,
    pull_number,
    mediaType: { format: "diff" },
  });

  // The diff is returned as the raw response data when the diff media type is requested
  const diff = /** @type {unknown} */ (response.data);
  if (typeof diff !== "string") {
    throw new Error("Unexpected diff format returned by the GitHub API.");
  }

  if (diff.length > MAX_DIFF_CHARS) {
    core.warning(
      `Diff is ${diff.length} characters — truncating to ${MAX_DIFF_CHARS} to stay within context limits.`
    );
    return diff.slice(0, MAX_DIFF_CHARS) + "\n\n[... diff truncated ...]";
  }

  return diff;
}

/**
 * Fetch pull-request metadata (title, body, base/head).
 */
async function fetchPrMetadata(octokit, { owner, repo, pull_number }) {
  const { data } = await octokit.rest.pulls.get({
    owner,
    repo,
    pull_number,
  });

  return {
    title: data.title,
    body: data.body ?? "(no description provided)",
    baseBranch: data.base.ref,
    headBranch: data.head.ref,
    additions: data.additions,
    deletions: data.deletions,
    changedFiles: data.changed_files,
    author: data.user?.login ?? "unknown",
  };
}

/**
 * Build the Gemini prompt from PR metadata and diff.
 */
function buildPrompt({ title, body, baseBranch, headBranch, additions, deletions, changedFiles, author, diff }) {
  return `You are a senior software engineer performing a thorough pull request review.

## Pull Request Details
- **Title**: ${title}
- **Author**: @${author}
- **Branch**: \`${headBranch}\` → \`${baseBranch}\`
- **Stats**: +${additions} additions, -${deletions} deletions across ${changedFiles} file(s)
- **Description**:
${body}

## Diff
\`\`\`diff
${diff}
\`\`\`

---

Please produce a concise, structured PR summary with the following sections. Use GitHub-flavoured Markdown.

### 📝 What Changed
A clear bullet-point list of the concrete changes introduced by this PR (files modified, new features, removed code, dependency updates, etc.).

### 💡 Why It Matters
Explain the purpose and business/technical value of these changes. Why was this work needed?

### ⚠️ Potential Concerns
Highlight any risks, edge cases, code smells, missing tests, security considerations, or areas that reviewers should scrutinise carefully. If the PR looks clean, say so.

### 📊 Complexity Score
Rate the overall complexity of this PR on a scale of **1–10** (1 = trivial typo fix, 10 = sweeping architectural change) and justify the score in one or two sentences.

Keep the summary factual, constructive, and under 600 words.`;
}

/**
 * Call the Gemini API and return the summary text.
 */
async function generateSummary(geminiApiKey, prompt) {
  const genAI = new GoogleGenerativeAI(geminiApiKey);
  const model = genAI.getGenerativeModel({ model: MODEL });

  const result = await model.generateContent(prompt);
  const text = result.response.text();

  if (!text) {
    throw new Error("Gemini returned no text content.");
  }

  return text;
}

/**
 * Find an existing bot comment on the PR (so we can update rather than spam).
 */
async function findExistingComment(octokit, { owner, repo, issue_number }) {
  const comments = await octokit.paginate(octokit.rest.issues.listComments, {
    owner,
    repo,
    issue_number,
  });

  return comments.find((c) => c.body?.includes(COMMENT_MARKER)) ?? null;
}

/**
 * Post or update the summary comment on the PR.
 */
async function upsertComment(octokit, { owner, repo, issue_number, body }) {
  const existing = await findExistingComment(octokit, { owner, repo, issue_number });

  const fullBody = `${COMMENT_MARKER}\n## 🤖 AI PR Summary\n\n${body}\n\n---\n<sub>Generated by [pr-summarizer](https://github.com/marketplace) using **${MODEL}**. Re-runs on every push.</sub>`;

  if (existing) {
    core.info(`Updating existing comment #${existing.id}`);
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body: fullBody,
    });
  } else {
    core.info("Creating new PR comment");
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number,
      body: fullBody,
    });
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function run() {
  try {
    // --- Inputs ---
    const githubToken = core.getInput("github-token", { required: true });
    const geminiApiKey = core.getInput("gemini-api-key", { required: true });

    // --- Context ---
    const { context } = github;
    const octokit = github.getOctokit(githubToken);

    if (!context.payload.pull_request) {
      core.setFailed("This action must be triggered by a pull_request event.");
      return;
    }

    const pull_number = context.payload.pull_request.number;
    const { owner, repo } = context.repo;

    core.info(`Summarizing PR #${pull_number} in ${owner}/${repo}`);

    // --- Fetch data ---
    core.startGroup("Fetching PR metadata");
    const metadata = await fetchPrMetadata(octokit, { owner, repo, pull_number });
    core.info(`Title: ${metadata.title}`);
    core.info(`Changed files: ${metadata.changedFiles} (+${metadata.additions}/-${metadata.deletions})`);
    core.endGroup();

    core.startGroup("Fetching PR diff");
    const diff = await fetchPrDiff(octokit, { owner, repo, pull_number });
    core.info(`Diff size: ${diff.length} characters`);
    core.endGroup();

    // --- Generate summary ---
    core.startGroup("Calling Gemini API");
    const prompt = buildPrompt({ ...metadata, diff });
    const summary = await generateSummary(geminiApiKey, prompt);
    core.info("Summary generated successfully");
    core.endGroup();

    // --- Post comment ---
    core.startGroup("Posting PR comment");
    await upsertComment(octokit, {
      owner,
      repo,
      issue_number: pull_number,
      body: summary,
    });
    core.endGroup();

    core.info("✅ PR summary posted successfully!");
  } catch (error) {
    core.setFailed(`Action failed: ${error instanceof Error ? error.message : String(error)}`);
  }
}

run();
